# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2f80df6b836619d0b2f5f6e69c3c67ff95fa9fed31d7680c861bd77dba4b33c36f74c7f11fd13145dbeb7c48a20310f1761e9a3f79dfdbba3833b7545278b12

test:
  secret_key_base: 740c86a919292491d88444f6e6ea3a311bda32e088ecab3e7396d83fba843e129ff029d2bcd967756fd9931b3a46590341116f76b60152f88fe3ad444586863f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
